
splash:
    connections:
        sylius:    
            name:           Sylius Server
            id:             ThisIsSyliusWsId
            key:            ThisIsSyliusWsEncryptionKey
            host:           http://toolkit.sylius.local/ws/soap
            config:
                infos:
                    ico:    https://sylius.com/wp-content/themes/sylius-v5/assets/src/media/img/fav/favicon-196x196.png
                    logo:   https://sylius.com/wp-content/uploads/2021/03/sylius-logo_sylius-logo-light-1024x422.jpg
    test:
        VAT:                0
        
splash_sylius_splash:
    default_channel:    FASHION_WEB
    