################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_DATABASE:         sylius
    MYSQL_ROOT_PASSWORD:    admin
    COMPOSER_MEMORY_LIMIT:  -1
    SYMFONY_DEPRECATIONS_HELPER:  disabled
    DATABASE_URL:           mysql://root:admin@mysql/sylius

################################################################
# Defined Pipeline Stages
stages:
  - deploy
  - quality
  - tests
#  - deploy

################################################################
# Code Quality Tests
################################################################
.quality:     &quality
  stage:      quality
  tags:
      - Dedicated
  services:
      - mysql:8.0
  ################################################################################
  # Install & Configure Environnement
  before_script:
      ################################################################################
      # Run Composer
      - composer require sylius/sylius $SYLIUS_VERSION --no-update --no-interaction
      - composer update --no-interaction --prefer-dist --no-scripts --no-plugins
  ################################################################################
  # Run Test Script
  script:
      # Execute Grumphp Testsuite
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/grumphp.sh  | sh
  ################################################################################
  # Run After Script
  after_script:
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

################################################################
# Tests on Sylius V1.12
quality:v1.12-php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    variables:
        SYLIUS_VERSION:   "~1.12.6"
    <<: *quality

################################################################
# Tests on Sylius V1.11
quality:v1.11-php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    variables:
        SYLIUS_VERSION:   "~1.11.15"
    <<: *quality

################################################################
# Tests on Sylius V1.10
quality:v1.10-php-7.4:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
    variables:
        SYLIUS_VERSION:   "~1.10.14"
    <<: *quality

################################################################
# Tests on Sylius V1.08
quality:v1.08-php-7.4:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
    variables:
        SYLIUS_VERSION:   "~1.08.12"
    <<: *quality

################################################################
# Functional Tests
################################################################

.core_tests:    &core_tests
    stage:      tests
    tags:
        - Dedicated
    services:
        - name: mysql:8.0
    artifacts:
        when: always
        reports:
            junit: "$CI_PROJECT_DIR/*-report.xml"
    ################################################################################
    # Install & Configure Environnement
    before_script:
      ################################################################################
      # Check if Sylius Core is Installed
      - sh /builds/SplashSync/Sylius-Bundle/docker/scripts/install-sylius-core.sh
      ################################################################################
      # Check if Sylius Database is Installed
      - sh /builds/SplashSync/Sylius-Bundle/docker/scripts/install-sylius-db.sh
      ################################################################################
      # Check if Splash Dev Module is Installed
      - sh /builds/SplashSync/Sylius-Bundle/docker/scripts/install-dev-module.sh
    ################################################################################
    # Run Test Script
    script:
      # Execute PhpUnit Tests
      - cd /var/www/html
      - php vendor/bin/phpunit --version
      - php vendor/bin/phpunit --log-junit $CI_PROJECT_DIR/main-report.xml

################################################################
# Tests on Sylius V1.12
tests:v1.12-php-8.1:
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    variables:
        SYLIUS_VERSION:   "~1.12.4"
    <<: *core_tests

################################################################
# Tests on Sylius V1.11
tests:v1.11-php-8.0:
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    allow_failure:  true
    variables:
        SYLIUS_VERSION:   "~1.11.4"
    <<: *core_tests

################################################################
# Tests on Sylius V1.10
tests:v1.10-php-7.4:
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
    allow_failure:  true
    variables:
        SYLIUS_VERSION:   "~1.10.2"
    <<: *core_tests

#################################################################
## Build Documentation
#################################################################
pages:
  image:      jekyll/minimal
  stage:      deploy
  tags:       [ Dedicated-Docker ]
  ################################################################################
  # Run Test Script
  script:
    - sh scripts/gitlab-pages.sh
  artifacts:
    paths:
      - public


#################################################################
## Build Documentation
#################################################################
#pages:
#    image:    registry.gitlab.com/badpixxel-projects/php-sdk:jekyll
#    stage:    deploy
#    tags:
#        - Dedicated
#    ################################################################################
#    # Run Test Script
#    script:
#        # Run Composer to Build deps
#        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
#        # Build Documentation
#        - php vendor/bin/grumphp run --tasks=build-docs
#    artifacts:
#        paths:
#            - public