# Project language
language: php

# Allows use container-based infrastructure
sudo: false
#sudo: required
#dist: trusty

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.cache/pip

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
#  fast_finish: true
  include:
#    - php: 5.5
#    - php: 5.6
#    - php: 7.0
    - php: 7.1
#    - php: 7.2
#    - php: hhvm
#  allow_failures:
#    - php: hhvm

# Define an environment variable
#env:
#  - SYMFONY_VERSION="3.0.*" DB=mysql

before_install:
# Update composer
  - composer self-update
# Install Yarn
  - yarn 
# Increase memory limit to 4GB  
  - phpenv config-rm xdebug.ini
  - phpenv config-add build/x_memory.ini
  - phpenv config-add build/x_errors.ini
  - php -ini | grep memory_limit  

# Install composer dependencies,
# Create database, schema and fixtures
install:   
    - composer create-project sylius/sylius-standard sylius --prefer-dist
    - cd sylius
#    - composer install --no-interaction --no-scripts --prefer-dist
#    - composer require splash/phpcore:dev-master --no-interaction --no-scripts --prefer-dist
#    - composer require splash/php-bundle:dev-master  --no-interaction --no-scripts --prefer-dist
#    - composer require splash/sylius-bundle:dev-master --no-interaction --no-scripts --prefer-dist
    - echo "Install Splash Bundles"
    - composer require splash/phpcore:dev-master splash/php-bundle:dev-master splash/sylius-bundle:dev-master --no-interaction --prefer-dist
    
    - echo "Configuring Splash Bundles"
    - cp ../build/parameters.yml.dist app/config/parameters.yml
    - cp ../build/phpunit.xml.dist phpunit.xml.dist
    - cp ../build/AppKernel.php app/AppKernel.php
    - cp ../build/autoload.php app/autoload.php
    - cat ../build/config_splash.yml    >> app/config/config.yml
    - cat ../build/routing_splash.yml   >> app/config/routing.yml
    
    - echo "Install Sylius"
    - php bin/console sylius:install --env=test --no-interaction
    - php bin/console sylius:fixtures:load --env=test --no-interaction
    - php bin/console server:start --env=test
#    - chmod -R 777 app/autoload.php
    

# Run script
script:
  - phpunit
  - phpunit

# After a build, send email notification with the build results
#notifications:
#  email: your_email