# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.cache/pip

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
#  fast_finish: true
  include:
#    - php: 5.5
#    - php: 5.6
#    - php: 7.0
    - php: 7.1
#    - php: 7.2
#    - php: hhvm
#  allow_failures:
#    - php: hhvm

# Define an environment variable
#env:
#  - SYMFONY_VERSION="3.0.*" DB=mysql

before-install:
# Update composer
  - composer self-update
# Install Yarn
  - yarn 
# Increase memory limit to 4GB  
  - phpenv config-rm xdebug.ini
  - phpenv config-add build/x_memory.ini
  - php -m

# Install composer dependencies,
# Create database, schema and fixtures
install:
    - composer create-project sylius/sylius-standard sylius --prefer-dist
    - cd sylius
#    - composer install --no-interaction --no-scripts --prefer-dist
    - php -dmemory_limit=4G /usr/local/bin/composer require splash/phpcore:dev-master --no-interaction --no-scripts --prefer-dist
    - php -dmemory_limit=4G /usr/local/bin/composer require splash/php-bundle:dev-master  --no-interaction --no-scripts --prefer-dist
    - php -dmemory_limit=4G /usr/local/bin/composer require splash/sylius-bundle:dev-master --no-interaction --no-scripts --prefer-dist
    - cp ../build/parameters.yml.dist app/config/parameters.yml
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
#  - php bin/console doctrine:fixtures:load -n --env=test
    - php bin/console sylius:install --env=test
    - php bin/console server:start --env=test

# Run script
script:
  - phpunit

# After a build, send email notification with the build results
#notifications:
#  email: your_email