################################################################################
# Specify versions of Php & Sylius to test against
################################################################################
# SYLIUS_VERSION => Branch of Sylius Standard Edition to test Against
matrix:
    include:
        
        - php: 7.4
          env: SYLIUS_VERSION=1.7
          
        - php: 7.4
          env: SYLIUS_VERSION=""  
          
    allow_failures:
        - env: SYLIUS_VERSION=""    
          
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true
        
################################################################################
# Install Update Composer, Configure Env. 
before_install:
    # Update composer
    - composer self-update
    # Install Yarn
    - yarn 
    # Increase memory limit to 4GB  
    - phpenv config-rm xdebug.ini
    - phpenv config-add travis/x_memory.ini
    - php -ini | grep memory_limit  
  
################################################################################
# Install composer dependencies,
# Create database, schema and fixtures
install:   
    
    ################################################################################
    # Run Composer Update
    - echo "Install Dependencies"
    - composer install --no-interaction --prefer-dist
    
    ################################################################################
    # Install Sylius Standard Project
    - echo "Install Sylius"
    - composer create-project sylius/sylius-standard sylius $SYLIUS_VERSION --prefer-dist
    - cd sylius
    - cp  ../travis/.env.dist ".env" 
    - php bin/console sylius:install --env=test --no-interaction --no-debug
    - php bin/console sylius:fixtures:load --env=test --no-interaction --no-debug
    
    ################################################################################
    # Install Splash Sylius Bundles
    - echo "Install Splash Bundles"
    - cp  ../travis/phpunit.xml.dist phpunit.xml.dist
    - cp  ../travis/config_splash.yml    config/packages/splash.yml
    - cp  ../travis/routing_splash.yml   config/routes/splash.yml
    - composer require splash/phpcore:dev-master splash/php-bundle:dev-master splash/sylius-bundle:dev-master --no-interaction --prefer-dist

    ################################################################################
    # Start Symfony WebServer
    - echo "Start Web Srever"
    - php bin/console server:start --env=test

################################################################################
# Run Tests Scripts
script:
    ################################################################################
    # Run Code Quality Checks Tests
    - cd ..
    - php vendor/bin/grumphp run --testsuite=travis
#    - php vendor/bin/grumphp run --testsuite=csfixer
    - php vendor/bin/grumphp run --testsuite=phpstan
    
    ################################################################################
    # Run Functionnal Tests
    - cd sylius
    - phpunit
#    - php vendor/bin/phpunit
#    - phpdbg -qrr -d memory_limit=-1 vendor/bin/phpunit

################################################################################
# General Configuration
################################################################################
language: php
os: linux
# Start mysql service
services:
  - mysql
# Cache composer packages so "composer install" is faster
cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.cache/pip
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always
