###########################################################
# Main Configuration
###########################################################
site_name: Sylius Splash Bundle 
site_dir: "../docs"
theme: readthedocs

repo_url: https://github.com/SplashSync/Sylius-Bundle

copyright:  <i class="fa fa-copyright" aria-hidden="true"></i> Copyright Splash Sync 2017 

###########################################################
# Site Contents
###########################################################
pages:
    - Home: index.md
    - Features: features.md
    - Installation: install.md
    - Test & Connect: connect.md
    - Configuration Reference: configuration.md
#    - Français :
#        - Accueil : fr/index.md
#    - About: about.md