###########################################################
# Main Configuration
###########################################################
site_name: Sylius Splash Bundle 
site_dir: "../docs"
theme: readthedocs

repo_url: https://github.com/mkdocs/mkdocs/

###########################################################
# Site Contents
###########################################################
pages:
    - Home: index.md
#    - About: about.md