services: 
    
    ########################################################################
    # Sylius Customer Object
    splash.sylius.object.customer:
        class:      Splash\Sylius\Objects\ThirdParty
        public:     true
        arguments:  
            - "@translator"
            - "@sylius.manager.customer"
            - "@sylius.repository.customer"
            - "@sylius.factory.customer"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "ThirdParty" }  

    ########################################################################
    # Sylius Address Object
    splash.sylius.object.address:
        class:      Splash\Sylius\Objects\Address
        public:     true
        arguments:  
            - "@translator"
            - "@sylius.manager.address"
            - "@sylius.repository.address"
            - "@sylius.factory.address"
            - "@sylius.repository.customer"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "Address" }  

    ########################################################################
    # Sylius Product Object
    splash.sylius.object.product:
        class:      Splash\Sylius\Objects\Product
        public:     true
        arguments:  
            - "@sylius.manager.product"
            - "@sylius.repository.product"
            - "@sylius.repository.product_variant"
            - "@splash.sylius.product.translations"
            - "@splash.sylius.product.images"
            - "@splash.sylius.product.pricing"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "Product" }  
            
    ########################################################################
    # Sylius Products Translations Management
    splash.sylius.product.translations:
        class:      Splash\Sylius\Services\ProductTranslationsManager
        public:     false
        arguments:  
            - "@sylius.factory.product_translation"
            - "@=service('sylius.repository.locale').findAll()"
            - "%splash_sylius%"     

    ########################################################################
    # Sylius Products Images Management
    splash.sylius.product.images:
        class:      Splash\Sylius\Services\ProductImagesManager
        public:     false
        arguments:  
            - "@router"
            - "@sylius.manager.product_image"            
            - "@sylius.factory.product_image"
            - "@liip_imagine.cache.manager"
            - "%splash_sylius%"     

    ########################################################################
    # Sylius Products Prices Management
    splash.sylius.product.pricing:
        class:      Splash\Sylius\Services\ProductPricingManager
        public:     false
        arguments:  
            - "@sylius.repository.channel"
            - "@sylius.manager.channel_pricing"            
            - "@sylius.factory.channel_pricing"
            - "%splash_sylius%"             
            
#    ########################################################################
#    # Sylius Object Data Transformer
#    # Convert In/Out Doctrine Objects Fields to Splash Standard Format
#    Splash.Sylius.Transformer:
#        class:      Splash\Sylius\Services\ObjectsTransformer
#        arguments:  ["@translator"]
#        
#    ########################################################################
#    # Sylius Products Data Transformer
#    # Convert In/Out Sylius Products Objects Fields to Splash Standard Format
#    Splash.Sylius.Products.Transformer:
#        class:      Splash\Sylius\Services\ProductTransformeruser
#        arguments:  
#         - "@translator"
#         - "@router"
#         - "@sylius.factory.product"
#         - "@sylius.manager.product"
#         - "@sylius.repository.channel"
#         - "%splash_sylius%"     
#         
#         
#    ########################################################################
#    # Sylius Orders Data Transformer
#    # Convert In/Out Sylius Orders Objects Fields to Splash Standard Format
#    Splash.Sylius.Orders.Transformer:
#        class:      Splash\Sylius\Services\OrdersTransformer
#        arguments:  
##         - "@translator"
##         - "@router"
##         - "@sylius.factory.product"
#         - "@sylius.manager.order"
#         - "@sylius.repository.channel"
#         - "%splash_sylius%"            
        
        
        
    ########################################################################
    # Sylius Additionnal Object Event Listener
    # This Listner is Triggered on Any Object changes dont on ORM
    # It will detect impacted Splash Objects and Dispatch Commits to Splash Server
    splash.sylius.objects.listener:
        class:      Splash\Sylius\EventListener\ObjectEventListener
        arguments:  
            - "@splash.connectors.manager"        
        tags:
            - { name: doctrine.event_listener, event: postPersist,  method: postPersist }
            - { name: doctrine.event_listener, event: postUpdate,   method: postUpdate }
            - { name: doctrine.event_listener, event: preRemove,    method: preRemove }
            