services: 

    _defaults:
        autowire:   true

    ########################################################################
    # Sylius Customer Object
    splash.sylius.object.customer:
        class:      Splash\SyliusSplashPlugin\Objects\ThirdParty
        public:     true
        arguments:  
            - "@translator"
            - "@sylius.manager.customer"
            - "@sylius.repository.customer"
            - "@sylius.factory.customer"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "ThirdParty" }  

    ########################################################################
    # Sylius Address Object
    splash.sylius.object.address:
        class:      Splash\SyliusSplashPlugin\Objects\Address
        public:     true
        arguments:
            - "@translator"
            - "@sylius.manager.address"
            - "@sylius.repository.address"
            - "@sylius.factory.address"
            - "@sylius.repository.customer"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "Address" }  

    ########################################################################
    # Sylius Product Object
    splash.sylius.object.product:
        class:      Splash\SyliusSplashPlugin\Objects\Product
        public:     true
        arguments:  
            - "@sylius.repository.product_variant"
            - "@splash.sylius.product.crud"
            - "@splash.sylius.product.translations"
            - "@splash.sylius.product.images"
            - "@splash.sylius.product.pricing"
            - "@splash.sylius.product.attributes"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "Product" }  

    ########################################################################
    # Sylius Products Crud Management
    splash.sylius.product.crud:
        class:      Splash\SyliusSplashPlugin\Services\ProductCrudManager
        public:     false
        arguments:  
            - "@sylius.manager.product"
            - "@sylius.repository.product"
            - "@sylius.repository.product_variant"
            - "@sylius.repository.channel"
            - "@sylius.factory.product"
            - "@sylius.factory.product_variant"
            - "%splash_sylius%" 
            
    ########################################################################
    # Sylius Products Translations Management
    splash.sylius.product.translations:
        class:      Splash\SyliusSplashPlugin\Services\ProductTranslationsManager
        public:     false
        arguments:  
            - "@sylius.factory.product_translation"
            - "@sylius.factory.product_option_translation"
            - "@sylius.factory.product_option_value_translation"
            - "@sylius.repository.locale"
            - "%splash_sylius%"

    ########################################################################
    # Sylius Products Images Management
    splash.sylius.product.images:
        class:      Splash\SyliusSplashPlugin\Services\ProductImagesManager
        public:     false
        arguments:  
            - "@router"
            - "@sylius.manager.product_image"            
            - "@sylius.factory.product_image"
            - "@liip_imagine.cache.manager"
            - "%splash_sylius%"     

    ########################################################################
    # Sylius Products Prices Management
    splash.sylius.product.pricing:
        class:      Splash\SyliusSplashPlugin\Services\ProductPricingManager
        public:     false
        arguments:  
            - "@sylius.repository.channel"
            - "@sylius.manager.channel_pricing"            
            - "@sylius.factory.channel_pricing"
            - "%splash_sylius%"             
          
    ########################################################################
    # Sylius Products Attributes Management
    splash.sylius.product.attributes:
        class:      Splash\SyliusSplashPlugin\Services\ProductAttributesManager
        public:     false
        arguments:  
            - "@sylius.manager.product_option"            
            - "@sylius.repository.product_option"
            - "@sylius.factory.product_option"
            - "@sylius.factory.product_option_value"
            - "@splash.sylius.product.translations"
            - "%splash_sylius%" 
        
    ########################################################################
    # Sylius Orders Object
    splash.sylius.order:
        class:      Splash\SyliusSplashPlugin\Objects\Order
        arguments:  
            - "@sylius.repository.order"
            - "@sylius.repository.channel"
            - "@sylius.repository.customer"
            - "@sylius.repository.address"
            - "@sylius.manager.order"
            - "@sylius.factory.order"
            - "@sm.factory"
            - "%splash_sylius%"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "Order" }  

    ########################################################################
    # Sylius Invoice Object
    splash.sylius.invoice:
        class:      Splash\SyliusSplashPlugin\Objects\Invoice
        arguments:  
            - "@sylius.repository.order"
            - "@sylius.repository.channel"
            - "@sylius.repository.customer"
            - "@sylius.repository.address"
            - "@sylius.manager.order"
            - "@sylius.factory.order"
            - "@sm.factory"
            - "%splash_sylius%"     
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "Invoice" }  

    ########################################################################
    # Sylius Tax Manager for Splash
    Splash\SyliusSplashPlugin\Services\TaxManager:
        arguments:
            - "%splash_sylius%"
            - "@sylius.repository.channel"
            - "@sylius.repository.tax_rate"

    ########################################################################
    # Sylius Units Manager for Splash
    Splash\SyliusSplashPlugin\Services\UnitsManager:
        arguments:
            - "%splash_sylius%"

    ########################################################################
    # Sylius Additional Object Event Listener
    # This Listener is Triggered on Any Object changes don't on ORM
    # It will detect impacted Splash Objects and Dispatch Commits to Splash Server
    Splash\SyliusSplashPlugin\EventListener\ObjectEventListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist,  method: postPersist }
            - { name: doctrine.event_listener, event: postUpdate,   method: postUpdate }
            - { name: doctrine.event_listener, event: preRemove,    method: preRemove }
