services: 
    
    ########################################################################
    # Splash Faker Generic Objects
    splash.sylius.object.customer:
        class:      Splash\Sylius\Objects\ThirdParty
        public:     true
        autowire:   true
        arguments:  
            - "@translator"
            - "@sylius.manager.customer"
            - "@sylius.repository.customer"
            - "@sylius.factory.customer"
        tags:
            # Register as Standalone Connector Object           
            - { name: "splash.standalone.object", type : "ThirdParty" }  

    
#    ########################################################################
#    # Sylius Object Data Transformer
#    # Convert In/Out Doctrine Objects Fields to Splash Standard Format
#    Splash.Sylius.Transformer:
#        class:      Splash\Sylius\Services\ObjectsTransformer
#        arguments:  ["@translator"]
#        
#    ########################################################################
#    # Sylius Products Data Transformer
#    # Convert In/Out Sylius Products Objects Fields to Splash Standard Format
#    Splash.Sylius.Products.Transformer:
#        class:      Splash\Sylius\Services\ProductTransformeruser
#        arguments:  
#         - "@translator"
#         - "@router"
#         - "@sylius.factory.product"
#         - "@sylius.manager.product"
#         - "@sylius.repository.channel"
#         - "%splash_sylius%"     
#         
#         
#    ########################################################################
#    # Sylius Orders Data Transformer
#    # Convert In/Out Sylius Orders Objects Fields to Splash Standard Format
#    Splash.Sylius.Orders.Transformer:
#        class:      Splash\Sylius\Services\OrdersTransformer
#        arguments:  
##         - "@translator"
##         - "@router"
##         - "@sylius.factory.product"
#         - "@sylius.manager.order"
#         - "@sylius.repository.channel"
#         - "%splash_sylius%"            
        
        
        
    ########################################################################
    # Sylius Additionnal Object Event Listener
    # This Listner is Triggered on Any Object changes dont on ORM
    # It will detect impacted Splash Objects and Dispatch Commits to Splash Server
    splash.sylius.objects.listener:
        class:      Splash\Sylius\EventListener\ObjectEventListener
        arguments:  
            - "@splash.connectors.manager"        
        tags:
            - { name: doctrine.event_listener, event: postPersist,  method: postPersist }
            - { name: doctrine.event_listener, event: postUpdate,   method: postUpdate }
            - { name: doctrine.event_listener, event: preRemove,    method: preRemove }
            