###########################################################
# Main Configuration
###########################################################
site_name: Sylius Splash Bundle 
site_dir: "../../docs"
theme: readthedocs

###########################################################
# Site Contents
###########################################################
pages:
    - Home: index.md
#    - About: about.md