###########################################################
# Main Configuration
###########################################################
site_name: Sylius Splash Bundle 

theme: readthedocs

###########################################################
# Site Contents
###########################################################
pages:
    - Home: index.md
#    - About: about.md